name: registry

on:
  push:
    branches:
      - "master"

env:
  REGISTRY: ghcr.io

jobs:
  push:
    strategy:
      fail-fast: false
      matrix:
        image: ['musl']

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/dockerfiles/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/dockerfiles/${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
